Parameters:
    pInstanceType:
        Description: Select EC2 Instance Type
        Type: String
        Default: t2.micro
        AllowedValues: 
            - t2.nano
            - t2.micro
            - t2.small
Mappings:
    mRegionMap:
        us-west-2:
            AMI: ami-0841edc20334f9287
        us-east-2:
            AMI: ami-0603cbe34fd08cb81
Resources:
  rWebServer:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !FindInMap
        - mRegionMap
        - !Ref 'AWS::Region'
        - AMI
      InstanceType:
        !Ref pInstanceType