AWSTemplateFormatVersion: 2010-09-09
Description: >
  Sample template to create an Windows Server and add Features

Parameters:
  pKeyName:
    Description: Select Key Pair
    Type: 'AWS::EC2::KeyPair::KeyName'
  pInstanceType:
    Description: Select EC2 Instance Type
    Type: String
    Default: t2.micro
    AllowedValues: 
      - t2.nano
      - t2.micro
      - t2.small
  pRDPSourceCidr:
    Description: Source CIDR you will RDP from...
    Type: String
    Default: 205.251.233.0/24
    MinLength: "9"
    MaxLength: "18"
    AllowedPattern: ^([0-9]+\.){3}[0-9]+\/[0-9]+$
#  pRoles:
#    Description: Select a role to install
#    Type: String
#    Default: None
    # AllowedPattern:
#    AllowedValues:
#      - DNS
#      - DHCP
#      - None
#  pFeatures:
#    Description: Select a feature to install
#    Type: String
#    Default: None
#    AllowedValues:
#      - Telnet-Client
#      - Backup-Features
#      - None
Mappings:
  mRegionMap:
    us-west-2:
      AMI: ami-0afb7a78e89642197
    us-east-2:
      AMI: ami-0ca69a9d06da3835d
Resources:
  rW2019:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !FindInMap
        - mRegionMap
        - !Ref 'AWS::Region'
        - AMI
      InstanceType:
        !Ref pInstanceType
      SecurityGroups:
        - !Ref rSecurityGroup
      KeyName:
        !Ref pKeyName
      UserData:
        Fn::Base64:
          Fn::Join:
            - ""
            - - |
                <script>
              - "cfn-init.exe -v -s "
              - Ref: AWS::StackId
              - " -r rW2019"
              - " --region "
              - Ref: AWS::Region
              - "\n"
              - </script>
    Metadata:
    # used by cfn-init.exe
      AWS::CloudFormation::Init:
        config:
          files:
          # config file for cfn-hup
            c:\cfn\cfn-hup.conf:
              content:
                Fn::Join:
                  - ""
                  - - |
                      [main]
                    - stack=
                    - Ref: AWS::StackId
                    - "\n"
                    - region=
                    - Ref: AWS::Region
                    - "\n"
          # config file for the hook used by cfn-hup to initiate an update, when the metadata in AWS::CloudFormation::Init changes
            c:\cfn\hooks.d\cfn-auto-reloader.conf:
              content:
                Fn::Join:
                  - ""
                  - - |
                      [cfn-auto-reloader-hook]
                    - |
                      triggers=post.update
                    - >
                      path=Resources.rW2019.Metadata.AWS::CloudFormation::Init
                    - "action=cfn-init.exe -v -s "
                    - Ref: AWS::StackId
                    - " -r rW2019"
                    - " --region "
                    - Ref: AWS::Region
                    - "\n"
          commands:
            1-install-something:
              command: PowerShell.exe -Command "Install-WindowsFeature Telnet-Client"
              #command: PowerShell.exe -Command "echo "hello" > c:\hello.txt"
          services:
            windows:
              cfn-hup:
                enabled: "true"
                ensureRunning: "true"
                files:
                  - c:\cfn\cfn-hup.conf
                  - c:\cfn\hooks.d\cfn-auto-reloader.conf

  rSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: RDP
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '3389'
          ToPort: '3389'
#          CidrIp: 205.251.233.0/24
          CidrIp: 
            Ref: pRDPSourceCidr

