AWSTemplateFormatVersion: 2010-09-09
Description: >
  Sample template for Database Migration Service (DMS)
# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/AWS_DMS.html
Metadata:
# Change the default order of the parameters
  AWS::CloudFormation::Interface:
    ParameterGroups:
      -
        Label:
          default: "Replication Instance"
        Parameters:
          - pReplicationInstanceClass
          - pReplicationInstanceStorage
          - pAvailabilityZone
      -
        Label:
          default: "Source Endpoints"
        Parameters:
          - pEPSrcDbEngine
          - pSrcServerName
          #- pSrcDbUsername
          #- pSrcDbPassword
      -
        Label:
          default: "Target Endpoints"
        Parameters:
          - pEPTgtDbEngine
          - pTgtServerName
          #- pTgtDbUsername
          #- pTgtDbPassword
      -
        Label:
          default: "Replication Task"
        Parameters:
          - pMigrationType
          - pDbSchemaName

Parameters:
  pReplicationInstanceClass:
    Description: Select Instance Class (Compute & Memory Capacity)
    Type: String
    Default: dms.t2.small
    AllowedValues:
      - dms.t2.micro
      - dms.t2.small
      - dms.t2.medium
  pReplicationInstanceStorage:
    Description: The amount of storage (in GB) to be allocated.
    Type: Number
    Default: 50
  pAvailabilityZone:
    Description: AZ of the Replication Instance
    Type: String
    Default: us-west-1b

  pEPSrcDbEngine:
    Description: Source DB Engine.
    Type: String
    Default: mysql
    AllowedValues: [mysql, oracle, postgres, mariadb, aurora, sqlserver]  
  pSrcServerName:  
    Description: Source DB Server Name
    Type: String
    Default: 172.31.28.3
  #pSrcDbUsername:
    #Description: Source DB Username
    #Type: String
    #Default: wpdbadmin
  #pSrcDbPassword:
    #Description: Source DB Password
    #Type: String

  pEPTgtDbEngine:
    Description: Target DB Engine.
    Type: String
    Default: mysql
    AllowedValues: [mysql, oracle, postgres, mariadb, aurora, sqlserver]
  pTgtServerName:  
    Description: Target DB Server Name
    Type: String
    Default: ab3targetdb.cmgtl5fnvnpm.us-west-1.rds.amazonaws.com
  #pTgtDbUsername:
    #Description: Target DB Username
    #Type: String
    #Default: xxadmin
  #pTgtDbPassword:
    #Description: Target DB Password
    #Type: String
  pMigrationType:
    Description: The migration type.
    Type: String
    Default: full-load
    AllowedValues: [full-load, cdc, full-load-and-cdc]
  pDbSchemaName:
    Description: DB Schema Name
    Type: String
    Default: wordpressdb

Resources:
# Replication Instance
  rReplicationInstance:
    Type: AWS::DMS::ReplicationInstance  
    Properties: 
      AllocatedStorage: !Ref pReplicationInstanceStorage
      MultiAZ: false
      PubliclyAccessible: false
      ReplicationInstanceClass: !Ref pReplicationInstanceClass
      ReplicationInstanceIdentifier: !Sub '${AWS::StackName}-RI'
      AvailabilityZone: !Ref pAvailabilityZone
# Endpoint Source
  rDMSEndpointSource:
    Type: AWS::DMS::Endpoint
    Properties: 
      EndpointIdentifier: !Sub '${AWS::StackName}-SourceEP'
      EndpointType: 'source'
      Port: 3306
      EngineName: !Ref pEPSrcDbEngine
      ServerName: !Ref pSrcServerName
      #Username: !Ref pSrcDbUsername
      #Password: !Ref pSrcDbPassword
      Username: '{{resolve:secretsmanager:SourceSM:SecretString:username}}' 
      Password: '{{resolve:secretsmanager:SourceSM:SecretString:password}}' 

  rDMSEndpointTarget:
    Type: AWS::DMS::Endpoint
    Properties: 
      EndpointIdentifier: !Sub '${AWS::StackName}-TargetEP'
      EndpointType: 'target'
      Port: 3306
      EngineName: !Ref pEPTgtDbEngine
      ServerName: !Ref pTgtServerName
      Username: '{{resolve:secretsmanager:TargetSM:SecretString:username}}'
      Password: '{{resolve:secretsmanager:TargetSM:SecretString:password}}'
# Replication Task
  rDMSReplicationTask:
    Type: AWS::DMS::ReplicationTask
    Properties:
      ReplicationTaskIdentifier: !Sub '${AWS::StackName}-dms-replication-task'
      MigrationType: !Ref pMigrationType
      ReplicationInstanceArn: !Ref rReplicationInstance
      SourceEndpointArn: !Ref rDMSEndpointSource
      TargetEndpointArn: !Ref rDMSEndpointTarget
      TableMappings:
        !Sub
          - |-
            {
              "rules": [
                {
                  "rule-type": "selection",
                  "rule-id": "1",
                  "rule-action": "include",
                  "object-locator": {
                    "schema-name": "${db_schema_name}",                          
                    "table-name": "%"
                  },
                  "rule-name": "1"
                }
              ]
            }                        
          -
            db_schema_name: !Ref pDbSchemaName      
      ReplicationTaskSettings:
        !Sub
          - |-
            {
              "FullLoadSettings": {
                "TargetTablePrepMode": "TRUNCATE_BEFORE_LOAD",
              }
            }   
          -
            enable_logging: true
                             
#Mappings:
#Outputs: