AWSTemplateFormatVersion: 2010-09-09
Description: >
  Sample template to create an EBS
Parameters:
  pSize:
    Description: Size in GB of EBS
    Type: String
Resources:
# Resource Name.  Prefixed with 'r'  
  rNewVolume:
# Attribute 'Type'
    Type: AWS::EC2::Volume
# Attribute 'Properties'    
    Properties: 
# Subproperties:    
      Size: !Ref pSize
      VolumeType: gp2
      AvailabilityZone: !Select
        - 0
        - Fn::GetAZs: !Ref 'AWS::Region'
#Mappings:
#Outputs:
