Parameters:
    pKeyName:
        Description: Select Key Pair
        Type: 'AWS::EC2::KeyPair::KeyName'
    pInstanceType:
        Description: Select EC2 Instance Type
        Type: String
        Default: t2.micro
        AllowedValues: 
            - t2.nano
            - t2.micro
            - t2.small
Mappings:
    mRegionMap:
        us-west-2:
            AMI: ami-0841edc20334f9287
        us-east-2:
            AMI: ami-0603cbe34fd08cb81
Resources:
  rWebServer:
    Type: AWS::EC2::Instance
    Metadata:
      'AWS::CloudFormation::Init':
        config:
          packages:
            yum:
              httpd: []
          files:
            /var/www/html/index.html:
              content: <html><body><h1>AWSome 2.0</h1></body></html>
              mode: '000644'
              owner: root
              group: root
          services:
            sysvinit:
              httpd:
                enabled: 'true'
                ensureRunning: 'true'
    Properties:
      ImageId: !FindInMap
        - mRegionMap
        - !Ref 'AWS::Region'
        - AMI
      KeyName: !Ref pKeyName
      InstanceType:
        !Ref pInstanceType
      SecurityGroups:
        - !Ref rSecurityGroup
      UserData: !Base64 
        'Fn::Join':
          - ''
          - - |
              #!/bin/bash -xe
            - |
              yum update -y aws-cfn-bootstrap
              # Python helper script to process metadata configs
            - '/opt/aws/bin/cfn-init -v '
            - '         --stack '
            - !Ref 'AWS::StackName'
            - '         --resource rWebServer '
            - '         --region '
            - !Ref 'AWS::Region'
            - |+
            
  rSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: CF Enable SSH and HTTP
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '22'
          ToPort: '22'
          CidrIp: 205.251.233.0/24
        - IpProtocol: tcp
          FromPort: '80'
          ToPort: '80'
          CidrIp: 205.251.233.0/24
Outputs:
  URL:
    Description: URL of Website
    Value: !Join
      - ''
      - - 'http://'
        - !GetAtt
          - rWebServer
          - PublicDnsName
  PublicIP:
    Description: Server Public IP
    Value:
      !GetAtt
        - rWebServer
        - PublicIp
      