Description: >
  Sample template to use a nested stack with Parameters
Parameters:
  pSize:
    Description: Nested Size
    Type: String
Resources:
  rStack01:
    Type: AWS::CloudFormation::Stack
    Properties:
      # path style and virtual hosted S3 links
      #TemplateURL: https://cf-templates-1ovuf5ib6qznn-us-west-2.s3-us-west-2.amazonaws.com/Sample01.yaml
      #TemplateURL: https://s3.us-west-2.amazonaws.com/cf-templates-1ovuf5ib6qznn-us-west-2/Sample01.yaml
      TemplateURL: https://cf-templates-1ovuf5ib6qznn-us-west-2.s3.us-west-2.amazonaws.com/Sample01.yaml
      Parameters: 
        pSize: !Ref 'pSize'
        